name: movieportal_flutter
description: "Movieportal Flutter is a Flutter mobile application for browsing and discovering movies."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.2

dependencies:
  flutter:
    sdk: flutter
  http: ^1.1.0
  flutter_dotenv: ^5.1.0
  cached_network_image: ^3.3.0
  provider: ^6.0.5
  dotenv: ^4.2.0
  flutter_svg: ^2.0.7
  http_status: ^3.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
